### ISSUE TITLE
An Error Was Encountered

### ISSUE THREAD

**Issue by djiesamsoe** [Kami/Open-Blog#3]
i'm try to open all page, an get error:
`The URI you submitted has disallowed characters.`

can resolve this?
example url:

``` http://localhost/blog/index.php/user/login```

Thanks
```

**Comment by JasonBaier** [comment]
Try replacing line 126 in /application/config/config.php with this:

`$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';`

**Comment by djiesamsoe** [comment]
thanks, it works now:+1:
